# Generated by Django 4.1.7 on 2023-03-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp_proj', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='liked_at',
        ),
    ]
